spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:admin}
      password: ${CONFIG_SERVER_PASSWORD:admin}
  datasource:
    url: jdbc:mysql://${PAYMENT_DB_HOST:localhost}:${PAYMENT_DB_PORT:3310}/payment_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootpassword}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://admin:admin@localhost:8761/eureka/}
  instance:
    preferIpAddress: false
    instanceId: ${spring.application.name}:${random.value}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.ecommerce: DEBUG
