# Inventory Service Configuration
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/inventory_service_db?useSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootpassword}

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    preferIpAddress: false
