spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${USER_DB_HOST:127.0.0.1}:${USER_DB_PORT:3406}/user_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:${MYSQL_ROOT_PASSWORD:rootpassword}}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://${USER_DB_HOST:127.0.0.1}:${USER_DB_PORT:3406}/user_service_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    user: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:${MYSQL_ROOT_PASSWORD:rootpassword}}

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    preferIpAddress: false
