spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_REPO_LOCATION:file:///c:/Projects/Enterprise-ECommerce/config-repo}
  security:
    user:
      name: admin
      password: ${CONFIG_SERVER_PASSWORD:admin}

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://admin:admin@localhost:8761/eureka/}
  instance:
    preferIpAddress: true

logging:
  level:
    root: INFO
